name: Build desktop artifacts

on:
  workflow_dispatch:

jobs:
  make:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm config set node-linker hoisted --location project
          pnpm install --frozen-lockfile

      - name: Install Windows packaging deps (7zip, nuget)
        if: runner.os == 'Windows'
        run: |
          choco install 7zip 7zip.commandline nuget.commandline zip -y
          # Ensure all potential locations for 7-Zip and Chocolatey shims are on PATH
          echo "C:\\Program Files\\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\\ProgramData\\chocolatey\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\\ProgramData\\chocolatey\\lib\\7zip.portable\\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\\Program Files\\Git\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          # Verify tools are available
          7z -h | Select-String "7-Zip"
          7za -h | Select-String "7-Zip"
          nuget help | Select-String "usage"
          where 7z
          where 7za
          where nuget
          zip -v | Select-String "Zip"
          where zip

      - name: Approve required pnpm build scripts
        run: |
          pnpm approve-builds --yes electron-winstaller esbuild @tailwindcss/oxide

      - name: Verify 7z and nuget in PATH
        if: runner.os == 'Windows'
        run: |
          where 7z
          where nuget
          
      - name: Build artifacts
        run: pnpm make

      - name: Upload mac artifacts
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: mac-artifacts
          path: |
            out/make/zip/darwin/**/*
            out/make/dmg/darwin/**/*

      - name: Upload windows artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            out/make/squirrel.windows/**/*
            out/make/zip/win32/**/*
