name: Build desktop artifacts
on:
  workflow_dispatch:
jobs:
  make:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm config set node-linker hoisted --location project
          pnpm install --frozen-lockfile
      - name: Make with Electron Forge
        run: pnpm run make
      # We use Forge MakerZIP, so no manual zipping is required
      - name: Upload Windows artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-artifacts
          path: out/make/zip/**/*
      - name: Upload macOS artifacts
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: mac-zip-artifacts
          path: out/make/zip/**/*
